import { chromium, type Browser } from "playwright";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";

const build = await Bun.build({ entrypoints: ["scripts/panel-browser-fixture.ts"], target: "browser" });
if (!build.success) throw new Error(String(build.logs));
const bundle = await build.outputs[0]!.text();
const server = Bun.serve({ hostname: "127.0.0.1", port: 0, fetch: (request) => new URL(request.url).pathname === "/fixture.js" ? new Response(bundle, { headers: { "Content-Type": "application/javascript" } }) : new Response('<html><body style="margin:0"><script type="module" src="/fixture.js"></script></body></html>', { headers: { "Content-Type": "text/html" } }) });
let browser: Browser | undefined;
try {
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const requests: string[] = [];
  page.on("request", (request) => { if (request.url().startsWith("https:")) requests.push(request.url()); });
  await page.goto(`http://127.0.0.1:${server.port}`);
  await page.getByRole("button", { name: "Panels", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Keep this card", exact: true }).count(), 0);
  await page.evaluate(() => (window as any).fixture.dock.setCursor(1));
  await page.getByRole("button", { name: "Follow updates", exact: true }).click();
  const frame = page.frameLocator("iframe");
  assert.equal(await page.locator("iframe").getAttribute("sandbox"), "");
  assert.equal(await frame.locator("script").count(), 0);
  await frame.getByText("View status", { exact: true }).click();
  assert.equal(await frame.getByText("Strength 10", { exact: true }).isVisible(), true);
  assert.equal(await page.evaluate(() => (window as any).compromised), undefined);
  assert.equal(requests.length, 0);
  const title = page.getByRole("button", { name: "Hero status", exact: true });
  await title.focus(); await title.press("ArrowRight");
  await page.evaluate(() => (window as any).fixture.dock.setCursor(2));
  assert.equal(await frame.getByText("Strength 10", { exact: true }).isVisible(), true, "cursor refresh must preserve checkbox state");
  await page.setViewportSize({ width: 360, height: 640 });
  const bounds = await page.locator(".pin").boundingBox();
  assert.ok(bounds && bounds.x >= 0 && bounds.x + bounds.width <= 360 && bounds.y + bounds.height <= 640);
  await mkdir(".cache", { recursive: true });
  await page.screenshot({ path: ".cache/panels-mobile.png" });
  await page.evaluate(() => { const { dock, turn } = (window as any).fixture; dock.setTurn({ ...turn, sourceFingerprint: "other-swipe", panels: [] }); });
  assert.equal(await page.locator("iframe").count(), 0, "new swipe must not expose old follow state");
  await page.evaluate(() => { const { dock, turn } = (window as any).fixture; dock.setTurn({ ...turn, chatId: "different" }); });
  assert.equal(await page.locator(".pin").count(), 0, "chat isolation");
  const timeout = await page.evaluate(async () => { try { await (window as any).fixture.renderPanelRule("a".repeat(30000) + "!", { id: "bad", title: "Bad", pattern: "(a+)+$", flags: "", template: "$1" }, 0); return false; } catch (e) { return String(e).includes("timed out"); } });
  assert.equal(timeout, true, "pathological regex must time out off the UI thread");
  const rendered = await page.evaluate(async () => await (window as any).fixture.renderPanelRule('[STATUS: Jay]', { id: "good", title: "Stats", pattern: "\\[STATUS: (.*?)\\]", flags: "g", template: "<div>$1</div>" }, 2));
  assert.equal(rendered[0].html, "<div>Jay</div>");
  await page.evaluate(() => { const { dock, turn } = (window as any).fixture; dock.setTurn(turn, 2); });
  const publish = async (revision: number, html: string, fingerprint = "source-1", status = "ready") => page.evaluate(({ revision, html, fingerprint, status }) => {
    const turn = (window as any).fixture.turn;
    window.dispatchEvent(new CustomEvent("vn-panel-export-v1", { detail: { version: 1, provider: "simtracker", chatId: turn.chatId, messageId: turn.messageId, swipeId: turn.swipeId, sourceFingerprint: fingerprint, cardId: "main", revision, title: "Live SimTracker", html, status } }));
  }, { revision, html, fingerprint, status });
  await publish(1, "<div>HP 10</div>");
  await page.getByRole("button", { name: /Panels/ }).click();
  const liveRow = page.locator(".candidate").filter({ hasText: "Live SimTracker" });
  await liveRow.getByRole("button", { name: "Follow updates" }).click();
  await publish(2, "<div>HP 20</div>");
  assert.equal(await page.frameLocator('iframe[title="Live SimTracker"]').getByText("HP 20").isVisible(), true);
  await publish(1, "<div>HP stale</div>");
  await publish(3, "<div>HP wrong swipe</div>", "other-swipe");
  assert.equal(await page.frameLocator('iframe[title="Live SimTracker"]').getByText("HP 20").isVisible(), true);
  await publish(3, "", "source-1", "removed");
  assert.equal(await page.locator('iframe[title="Live SimTracker"]').count(), 0);
  await page.getByRole("button", { name: /Panels/ }).click();
  await page.locator(".candidate").filter({ hasText: "Hero status" }).getByRole("button", { name: "Keep this card" }).click();
  await page.reload();
  await page.locator('.pin').first().waitFor();
  assert.equal(await page.locator('iframe[title="Hero status"]').count(), 1, "only explicit snapshot survives before reveal after reload");
  console.log("Browser checks passed: reveal timing, CSS checkbox, script and network isolation, keyboard movement, mobile bounds, swipe/chat isolation, worker timeout.");
} finally { await browser?.close(); server.stop(); }
