import { chromium, type Browser } from "playwright";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";

const build = await Bun.build({ entrypoints: ["scripts/panel-browser-fixture.ts"], target: "browser" });
if (!build.success) throw new Error(String(build.logs));
const bundle = await build.outputs[0]!.text();
const server = Bun.serve({ hostname: "127.0.0.1", port: 0, fetch: (request) => new URL(request.url).pathname === "/fixture.js" ? new Response(bundle, { headers: { "Content-Type": "application/javascript" } }) : new Response('<html><body style="margin:0"><script type="module" src="/fixture.js"></script></body></html>', { headers: { "Content-Type": "text/html" } }) });
let browser: Browser | undefined;
try {
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const requests: string[] = [];
  page.on("request", (request) => { if (request.url().startsWith("https:")) requests.push(request.url()); });
  await page.goto(`http://127.0.0.1:${server.port}`);
  await page.getByRole("button", { name: "Panels", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Pin this card", exact: true }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "Capture SimTracker snapshot" }).isVisible(), false);
  await page.getByText("Advanced tools", { exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Capture SimTracker snapshot" }).isVisible(), true);
  await page.getByText("Advanced tools", { exact: true }).click();
  await page.evaluate(() => (window as any).fixture.dock.setCursor(1));
  await mkdir(".cache", { recursive: true });
  await page.screenshot({ path: ".cache/panels-basic-desktop.png" });
  await page.setViewportSize({ width: 360, height: 640 });
  const drawerBounds = await page.locator(".drawer").boundingBox();
  assert.ok(drawerBounds && drawerBounds.x >= 0 && drawerBounds.x + drawerBounds.width <= 360 && drawerBounds.y + drawerBounds.height <= 640, "Panels drawer fits mobile viewport");
  await page.screenshot({ path: ".cache/panels-basic-mobile.png" });
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.getByRole("button", { name: "Keep it updated", exact: true }).click();
  const frame = page.frameLocator("iframe");
  assert.equal(await page.locator("iframe").getAttribute("sandbox"), "");
  assert.equal(await frame.locator("script").count(), 0);
  await frame.getByText("View status", { exact: true }).click();
  assert.equal(await frame.getByText("Strength 10", { exact: true }).isVisible(), true);
  assert.equal(await page.evaluate(() => (window as any).compromised), undefined);
  assert.equal(requests.length, 0);
  const title = page.getByRole("button", { name: "Hero status", exact: true });
  await title.focus(); await title.press("ArrowRight");
  await page.evaluate(() => (window as any).fixture.dock.setCursor(2));
  assert.equal(await frame.getByText("Strength 10", { exact: true }).isVisible(), true, "cursor refresh must preserve checkbox state");
  await page.evaluate(() => (window as any).fixture.dock.setCursor(0));
  assert.equal(await page.locator("iframe").count(), 0, "rewinding before a followed card hides its future state");
  await page.evaluate(() => (window as any).fixture.dock.setCursor(2));
  assert.equal(await page.locator("iframe").count(), 1);
  await page.setViewportSize({ width: 360, height: 640 });
  const bounds = await page.locator(".pin").boundingBox();
  assert.ok(bounds && bounds.x >= 0 && bounds.x + bounds.width <= 360 && bounds.y + bounds.height <= 640);
  await mkdir(".cache", { recursive: true });
  await page.screenshot({ path: ".cache/panels-mobile.png" });
  await page.evaluate(() => { const { dock, turn } = (window as any).fixture; dock.setTurn({ ...turn, sourceFingerprint: "other-swipe", panels: [] }); });
  assert.equal(await page.locator("iframe").count(), 0, "new swipe must not expose old follow state");
  await page.evaluate(() => { const { dock, turn } = (window as any).fixture; dock.setTurn({ ...turn, chatId: "different" }); });
  assert.equal(await page.locator(".pin").count(), 0, "chat isolation");
  const timeout = await page.evaluate(async () => { try { await (window as any).fixture.renderPanelRule("a".repeat(30000) + "!", { id: "bad", title: "Bad", pattern: "(a+)+$", flags: "", template: "$1" }, 0); return false; } catch (e) { return String(e).includes("timed out"); } });
  assert.equal(timeout, true, "pathological regex must time out off the UI thread");
  const rendered = await page.evaluate(async () => await (window as any).fixture.renderPanelRule('[STATUS: Jay]', { id: "good", title: "Stats", pattern: "\\[STATUS: (.*?)\\]", flags: "g", template: "<div>$1</div>" }, 2));
  assert.equal(rendered[0].html, "<div>Jay</div>");
  await page.evaluate(() => { const { dock, turn } = (window as any).fixture; dock.setTurn(turn, 2); });
  const publish = async (revision: number, html: string, fingerprint = "source-1", status = "ready") => page.evaluate(({ revision, html, fingerprint, status }) => {
    const turn = (window as any).fixture.turn;
    window.dispatchEvent(new CustomEvent("vn-panel-export-v1", { detail: { version: 1, provider: "simtracker", chatId: turn.chatId, messageId: turn.messageId, swipeId: turn.swipeId, sourceFingerprint: fingerprint, cardId: "main", revision, title: "Live SimTracker", html, status } }));
  }, { revision, html, fingerprint, status });
  await publish(1, "<div>HP 10</div>");
  await page.getByRole("button", { name: /Panels/ }).click();
  const liveRow = page.locator(".candidate").filter({ hasText: "Live SimTracker" });
  await liveRow.getByRole("button", { name: "Keep it updated" }).click();
  await publish(2, "<div>HP 20</div>");
  assert.equal(await page.frameLocator('iframe[title="Live SimTracker"]').getByText("HP 20").isVisible(), true);
  await publish(1, "<div>HP stale</div>");
  await publish(3, "<div>HP wrong swipe</div>", "other-swipe");
  assert.equal(await page.frameLocator('iframe[title="Live SimTracker"]').getByText("HP 20").isVisible(), true);
  await publish(3, "", "source-1", "removed");
  assert.equal(await page.locator('iframe[title="Live SimTracker"]').count(), 0);
  await page.getByRole("button", { name: /Panels/ }).click();
  await page.locator(".candidate").filter({ hasText: "Hero status" }).getByRole("button", { name: "Pin this card" }).click();
  await page.reload();
  await page.locator('.pin').first().waitFor();
  assert.equal(await page.locator('iframe[title="Hero status"]').count(), 1, "only explicit snapshot survives before reveal after reload");
  // Settings smoke check only: the full settings flow lives in scripts/test-settings-browser.ts.
  await page.goto(`http://127.0.0.1:${server.port}/?settings`);
  const settings = page.locator("[data-vn-settings]");
  assert.equal(await settings.locator('[name="mode"]').isVisible(), true);
  for (const name of ["parserParameters", "imageParameters", "customCss", "ignoredTags", "debugLogging", "imageModel"]) {
    assert.equal(await settings.locator(`[name="${name}"]`).isVisible(), false, name + " should be advanced");
  }
  await settings.getByRole("heading", { name: "Appearance", exact: true }).click();
  await settings.locator('input[name="themePreset"][value="paper-novel"]').check();
  assert.deepEqual(await page.evaluate(() => (window as any).settingsFixture.saved), { themePreset: "paper-novel" });
  await page.screenshot({ path: ".cache/settings-basic-mobile.png", fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, "settings fit mobile width");
  await page.setViewportSize({ width: 1000, height: 900 });
  await page.screenshot({ path: ".cache/settings-basic-desktop.png", fullPage: true });
  await page.goto(`http://127.0.0.1:${server.port}/?navigation`);
  await page.emulateMedia({ reducedMotion: "reduce" });
  const previous = page.getByRole("button", { name: "Previous paragraph", exact: true });
  const next = page.getByRole("button", { name: "Continue", exact: true });
  const skip = page.getByRole("button", { name: "Skip", exact: true });
  const position = () => page.evaluate(() => (window as any).navigationFixture.stage.getState().currentParagraphIndex);
  assert.equal(await previous.isDisabled(), true);
  await next.press("Enter"); await next.press("Enter");
  assert.equal(await position(), 2);
  await previous.click();
  assert.equal(await position(), 1);
  assert.equal(await page.locator("[data-vn-speaker]").textContent(), "Speaker 1");
  await skip.click();
  await page.waitForFunction(() => (window as any).navigationFixture.stage.getState().phase === "awaiting-input");
  assert.equal(await position(), 2, "read-only skip works after going back");
  const draft = page.locator("[data-vn-input]");
  await draft.fill("Keep my draft");
  await draft.press("ArrowLeft");
  assert.equal(await position(), 2, "Left Arrow in the response field only moves the caret");
  await previous.click();
  assert.equal(await page.evaluate(() => (window as any).navigationFixture.stage.getState().draft), "Keep my draft");
  await page.evaluate(() => (window as any).navigationFixture.stage.focus());
  await page.keyboard.press("ArrowLeft");
  assert.equal(await position(), 0);
  await next.press("Enter");
  await page.getByRole("button", { name: "Auto play", exact: true }).click();
  await previous.click();
  assert.equal(await page.getByRole("button", { name: "Auto play", exact: true }).getAttribute("data-vn-active"), "false");
  assert.equal(await skip.getAttribute("data-vn-active"), "false");
  assert.deepEqual(await page.evaluate(() => (window as any).navigationFixture.previous), [1, 1, 0, 0]);
  await page.setViewportSize({ width: 360, height: 640 });
  const controlsBounds = await page.locator("[data-vn-controls]").boundingBox();
  const speakerBounds = await page.locator("[data-vn-speaker]").boundingBox();
  assert.ok(controlsBounds && speakerBounds && controlsBounds.y + controlsBounds.height <= speakerBounds.y, "mobile controls do not cover the nameplate");
  await page.screenshot({ path: ".cache/navigation-mobile.png" });
  console.log("Browser checks passed: backward navigation, read-only skip, playback pause; basic/advanced disclosure, hidden-value preservation, validation recovery, mobile settings; reveal timing, CSS checkbox, script and network isolation, keyboard movement, mobile bounds, swipe/chat isolation, worker timeout.");
} finally { await browser?.close(); server.stop(); }
